version: '3'
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   platform: linux/amd64
  #   working_dir: /app-frontend
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD", "lsof", "-t", "-i:3000"]
  #     timeout: 10s
  #     retries: 5
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    platform: linux/amd64
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  database:
    image: mysql:8.0.26
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - .env    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5  