version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    working_dir: /app-frontend
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    working_dir: /app-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: mysql:8.0.26
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/seed_script.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 5  